-name: "Red Rice (Walay)"
icon: "ЁЯМ╛"
image: "/images/products/red-rice.jpg"
description: "Naturally grown in Konkan using traditional methods."
description_mr: "рдХреЛрдХрдгрд╛рдд рдкрд╛рд░рдВрдкрд░рд┐рдХ рдкрджреНрдзрддреАрдиреЗ рдкрд┐рдХрд╡рд▓реЗрд▓рд╛ рд╡рд╛рд▓рдИ рддрд╛рдВрджреВрд│"
whatsapp_text: "Interested in Organic Red Rice from Kalyani Farms"

derived_products:
  -name: "Hand Pounded Rice"
   name_mr: "рд╣рд╛рддрд╕рдбреАрдЪрд╛ рддрд╛рдВрджреВрд│"
   image: "/images/products/rice1.jpg"
   whatsapp_text: "Interested in Hand Pounded Rice"
  
  -name: "Parboiled Rice"
   name_mr: "рдЙрдХрдбрд╛ рддрд╛рдВрджреВрд│"
   image: "/images/products/rice2.jpg"
   whatsapp_text: "Interested in Parboiled Rice"
  
  -name: "Rice Tukda"
   name_mr: "рддрд╛рдВрджреВрд│ рддреБрдХрдбрд╛"
   image: "/images/products/rice3.jpg"
   whatsapp_text: "Interested in Rice Tukda"
  
  -name: "Rice Flakes"
   name_mr: "рддрд╛рдВрджреВрд│ рдкреЛрд╣реЗ"
   image: "/images/products/rice4.jpg"
   whatsapp_text: "Interested in Rice Flakes"
  
  -name: "Rice Flour"
   name_mr: "рддрд╛рдВрджреВрд│ рдкреАрда"
   image: "/images/products/rice5.jpg"
   whatsapp_text: "Interested in Rice Flour"

-name: "Turmeric"
icon: "ЁЯМ┐"
image: "/images/products/turmeric.jpg"
description: "Sun-dried, chemical-free turmeric roots."
description_mr: "рдиреИрд╕рд░реНрдЧрд┐рдХ рдкрджреНрдзрддреАрдиреЗ рд╕реБрдХрд╡рд▓реЗрд▓реА рд╕реЗрдВрджреНрд░рд┐рдп рд╣рд│рдж"
whatsapp_text: "Interested in Organic Turmeric"

derived_products:
  -name: "Turmeric Powder"
  name_mr: "рд╣рд│рдж рдкрд╛рд╡рдбрд░"
  image: "/images/products/turmeric-powder.jpg"
  whatsapp_text: "Interested in Turmeric Powder"

