- name: "Red Rice (Walay)"
  icon: "🌾"
  image: "images/products/red-rice.jpg"
  description: "Naturally grown in Konkan using traditional methods."
  description_mr: "कोकणात पारंपरिक पद्धतीने पिकवलेला वालई तांदूळ"
  whatsapp_text: "Interested in Organic Red Rice from Kalyani Farms"

  derived_products:
    - name: "Hand Pounded Rice"
      name_mr: "हातसडीचा तांदूळ"
      image: "images/products/rice1.jpg"
      whatsapp_text: "Interested in Hand Pounded Rice"
    
    - name: "Parboiled Rice"
      name_mr: "उकडा तांदूळ"
      image: "images/products/rice2.jpg"
      whatsapp_text: "Interested in Parboiled Rice"
    
    - name: "Rice Tukda"
      name_mr: "तांदूळ तुकडा"
      image: "images/products/rice3.jpg"
      whatsapp_text: "Interested in Rice Tukda"
    
    - name: "Rice Flakes"
      name_mr: "तांदूळ पोहे"
      image: "images/products/rice4.jpg"
      whatsapp_text: "Interested in Rice Flakes"
    
    - name: "Rice Flour"
      name_mr: "तांदूळ पीठ"
      image: "images/products/rice5.jpg"
      whatsapp_text: "Interested in Rice Flour"

- name: "Turmeric"
  icon: "🌿"
  image: "images/products/turmeric.jpeg"
  description: "Sun-dried, chemical-free turmeric roots."
  description_mr: "नैसर्गिक पद्धतीने सुकवलेली सेंद्रिय हळद"
  whatsapp_text: "Interested in Organic Turmeric"

  derived_products:
  - name: "Turmeric Powder"
    name_mr: "हळद पावडर"
    image: "images/products/turmeric-powder.jpg"
    whatsapp_text: "Interested in Turmeric Powder"
 
  - name: "Turmeric Powder with black pepper"
    name_mr: "हळद पावडर"
    image: "images/products/turmeric-bppowder.jpg"
    whatsapp_text: "Interested in Turmeric Powder black pepper"

  - name: "Raw Turmeric Pickle"
    name_mr: "हळदीचे लोणचे"
    image: "images/products/turmeric-pickle.jpg"
    whatsapp_text: "Interested in Turmeric Pickle"

- name: "Black Pepper"
  icon: "🌿"
  image: "images/products/black-pepper.jpg"
  description: "Sun-dried, chemical-free Black Pepper."
  description_mr: "नैसर्गिक पद्धतीने सुकवलेली काळी मिरी"
  whatsapp_text: "Interested in Organic Black Pepper"
  
- name: "Pigeon Pea/Toor Dal"
  icon: "🌿"
  image: "images/products/toor.jpg"
  description: "Sun-dried, chemical-free,unpolished Toor Dal."
  description_mr: "तुरीची डाळ"
  whatsapp_text: "Interested in Organic Toor Dal"

- name: "Desi(Malvani) Onion"
  icon: "🌿"
  image: "images/products/onion.jpg"
  description: "Naturally grown in Konkan using traditional methods."
  description_mr: "कोकणात पारंपरिक पद्धतीने पिकवलेला कांदा"
  whatsapp_text: "Interested in Organic Onion"
  
- name: "Lesser Yam"
  icon: "🌿"
  image: "images/products/lesser-yam.jpg"
  description: "Naturally grown in Konkan using traditional methods."
  description_mr: "कोकणात पारंपरिक पद्धतीने पिकवलेला काटे कणगे"
  whatsapp_text: "Interested in Organic Onion"
  
  
